### PR TITLE
Eviscerated image-editor.

### LINKED ISSUE #87: Image edit pane
Only:

Start, end and URL fields

Hide everything else

### PR DESCRIPTION
**Pull request by secretrobotron**
Removed all functionality except start/end/URL.

Fixes #87.

### CODE REVIEW

**Comment by secretrobotron** [comment]
@Laurian review?

**Comment by Laurian** [comment]
lemme see ;)

**Review by Laurian — APPROVED** [review]
On a quick scan looks sane, but I know very little this codebase ;)

**Comment by Laurian** [comment]
second pass, things look good.

**Comment by secretrobotron** [comment]
Awesome :). Can you give it a whirl on your local instance to see that it doesn't crash?

**Comment by Laurian** [comment]
I have some resizing issue when adding an image, let me compare with master

**Comment by Laurian** [comment]
Actually even on master, if I add an image, I cannot change the URL to something else than the popcorn maker svg (does not show in timeline), and the image is always 0 height, and resizing it shows while resizing but in resize end it colapses to 0 height again, weird.

**Comment by Laurian** [comment]
I have the same issue on https://archive.org/pop/editor.html I'm on Chrome, this is weird... cc @benrito

**Comment by Laurian** [comment]
This is what I see on master and this pr, I wonder why...

**Comment by secretrobotron** [comment]
@Laurian yeah, totes. We should land https://github.com/mozilla/popcorn-editor/pull/93 first.

**Pull request merged**
