### PR TITLE
Fixed image plugin size problems.

### LINKED ISSUE #64: Images don't import
Tried to import images - is there something I'm doing wrong?

### PR DESCRIPTION
**Pull request by secretrobotron**
More specific & inclusive css for image plugin container. Directives for ui-resizable in additional jquery-ui css were stealing the show.

Fixes #64.

### CODE REVIEW

**Comment by secretrobotron** [comment]
@benrito who else is working on this code that can sanity-check before merging?

**Comment by benrito** [comment]
@traceypooh and @Laurian — @fishbowlescape might be able to do a user review.

gracias!

**Comment by secretrobotron** [comment]
@benrito, @fishbowlescape isn't a user. Typo?

**Comment by secretrobotron** [comment]
cc @futuresoup

**Pull request merged**
